-- AlterTable
ALTER TABLE `users` MODIFY `birthdate` DATE NOT NULL DEFAULT ('2023-12-01');

-- CreateTable
CREATE TABLE `AI` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` INTEGER UNSIGNED NOT NULL,
    `SS` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `SA` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `TM` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `BC` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `DR` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `TO` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `ST` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `DD` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `TR` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `PF` ENUM('NA', 'DEFICIENTE', 'MEJORABLE', 'BUENO', 'MUY_BUENO', 'EXCEPCIONAL') NOT NULL DEFAULT 'NA',
    `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NULL,

    INDEX `AI_user_id_foreign`(`user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `AI` ADD CONSTRAINT `AI_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
